services:
  frontendmentor-playground-service:
    container_name: frontendmentor-playground-container
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        USER_NAME: ${USER_NAME:-node}
        USER_GROUP_NAME: ${USER_GROUP_NAME:-workspace}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    tty: true
    volumes:
      - .:/workspace:cached
      - fm-qr-code-node-modules:/workspace/challenges/newbie/qr-code-component/node_modules
      - fm-blog-preview-card-node-modules:/workspace/challenges/newbie/blog-preview-card/node_modules
      - fm-social-links-node-modules:/workspace/challenges/newbie/social-links-profile/node_modules
      - fm-recepe-page-node-modules:/workspace/challenges/newbie/recipe-page/node_modules
      - fm-3-column-preview-card-component:/workspace/challenges/newbie/3-column-preview-card-component/node_modules
      - fm-faq-accordion:/workspace/challenges/newbie/faq-accordion/node_modules

    ports:
      - 5555:5555

volumes:
  fm-qr-code-node-modules:
  fm-blog-preview-card-node-modules:
  fm-social-links-node-modules:
  fm-recepe-page-node-modules:
  fm-3-column-preview-card-component:
  fm-faq-accordion: