sudo chown node /workspace/challenges/newbie/qr-code-component/node_modules
sudo chown node /workspace/challenges/newbie/blog-preview-card/node_modules
sudo chown node /workspace/challenges/newbie/social-links-profile/node_modules
sudo chown node /workspace/challenges/newbie/recipe-page/node_modules
sudo chown node /workspace/challenges/newbie/3-column-preview-card-component/node_modules
sudo chown node /workspace/challenges/newbie/faq-accordion/node_modules
sudo chown node /workspace/challenges/newbie/interactive-rating-component/node_modules
sudo chown node /workspace/challenges/newbie/apparel-coming-soon/node_modules
sudo chown node /workspace/challenges/newbie/sign-up-form-component/node_modules
sudo chown node /workspace/challenges/newbie/single-price-grid-component/node_modules
sudo chown node /workspace/challenges/newbie/ping-coming-soon-page/node_modules